/// Flutter icons CustomArrow
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomArrow
///      fonts:
///       - asset: fonts/CustomArrow.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomArrow {
  CustomArrow._();

  static const _kFontFam = 'CustomArrow';
  static const String? _kFontPkg = null;

  static const IconData share = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
